#ifndef LIFETRAC_MURATA_L072_RESET_CAUSE_H
#define LIFETRAC_MURATA_L072_RESET_CAUSE_H

#include <stdint.h>

typedef enum reset_cause_e {
    RESET_CAUSE_UNKNOWN = 0x00U,
    RESET_CAUSE_LPWR = 0x01U,
    RESET_CAUSE_WWDG = 0x02U,
    RESET_CAUSE_IWDG = 0x03U,
    RESET_CAUSE_SOFT = 0x04U,
    RESET_CAUSE_POR_BOR = 0x05U,
    RESET_CAUSE_PIN = 0x06U,
    RESET_CAUSE_OBL = 0x07U,
    RESET_CAUSE_FW = 0x08U
} reset_cause_t;

#endif /* LIFETRAC_MURATA_L072_RESET_CAUSE_H */