#!/usr/bin/env python3
"""Generate Python constants from tractor_h7/murata_host/mh_wire.h."""

from __future__ import annotations

import argparse
import pathlib
import re
from typing import Dict

DEFINE_RE = re.compile(r"^\s*#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(.+?)\s*$")
NUM_SUFFIX_RE = re.compile(r"\b(0[xX][0-9A-Fa-f]+|\d+)(?:[uUlL]+)\b")


def _sanitize_expr(expr: str) -> str:
    expr = expr.split("/*", 1)[0]
    expr = expr.split("//", 1)[0]
    expr = expr.strip()
    expr = NUM_SUFFIX_RE.sub(r"\1", expr)
    return expr


def _eval_expr(expr: str, env: Dict[str, int]) -> int:
    # Expressions in mh_wire.h are integer literals and arithmetic over prior defines.
    value = eval(expr, {"__builtins__": {}}, env)
    if not isinstance(value, int):
        raise ValueError(f"non-integer expression result: {expr}")
    return int(value)


def parse_header(header_path: pathlib.Path) -> Dict[str, int]:
    env: Dict[str, int] = {}
    for raw_line in header_path.read_text(encoding="utf-8").splitlines():
        match = DEFINE_RE.match(raw_line)
        if not match:
            continue

        name = match.group(1)
        if "(" in name:
            continue

        expr = _sanitize_expr(match.group(2))
        if not expr:
            continue

        try:
            env[name] = _eval_expr(expr, env)
        except Exception:
            # Skip defines outside the integer subset used by the host protocol.
            continue

    return env


def render_module(constants: Dict[str, int], header_rel: str) -> str:
    lines = []
    lines.append("# Auto-generated by tools/gen_mh_wire_py.py")
    lines.append(f"# Source: {header_rel}")
    lines.append("")

    for key in sorted(constants):
        lines.append(f"{key} = {constants[key]}")

    lines.append("")
    lines.append("ALL = {")
    for key in sorted(constants):
        lines.append(f"    \"{key}\": {key},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--header",
        type=pathlib.Path,
        default=None,
        help="Path to mh_wire.h (default: repository tractor_h7 mirror)",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=None,
        help="Output Python module path (default: tools/mh_wire_constants.py)",
    )
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parents[1]
    header = args.header or (root / "firmware" / "tractor_h7" / "murata_host" / "mh_wire.h")
    output = args.output or (root / "tools" / "mh_wire_constants.py")

    constants = parse_header(header)
    text = render_module(constants, str(header.relative_to(root)))
    output.write_text(text, encoding="utf-8")

    print(f"generated {len(constants)} constants -> {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
