"""Generate the local LifeTrac v25 LoRa fleet-key header.

This implements the MASTER_PLAN.md v25 key workflow: a single shared AES-128
key lives in firmware/common/lora_proto/key.h on each build machine and is not
committed. Device flashing over USB can be layered on this once the bootloader
handshake is defined.
"""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_HEADER = ROOT / "firmware" / "common" / "lora_proto" / "key.h"


def parse_key(text: str | None) -> bytes:
    if text is None:
        return secrets.token_bytes(16)
    cleaned = text.replace(" ", "").replace(":", "").replace("-", "")
    key = bytes.fromhex(cleaned)
    if len(key) != 16:
        raise ValueError("AES-128 fleet key must be exactly 16 bytes / 32 hex chars")
    return key


def default_key_id(key: bytes) -> int:
    value = 0x811C9DC5
    for byte in key:
        value ^= byte
        value = (value * 0x01000193) & 0xFFFFFFFF
    return value or 1


def render_header(key: bytes, key_id: int) -> str:
    rows = []
    for idx in range(0, 16, 4):
        row = ", ".join(f"0x{byte:02X}" for byte in key[idx:idx + 4])
        rows.append(f"      {row}")
    return """#ifndef LIFETRAC_LORA_KEY_H
#define LIFETRAC_LORA_KEY_H

#include <stdint.h>

// Generated by DESIGN-CONTROLLER/tools/provision.py.
// Do not commit this file.

#define LIFETRAC_KEY_ID 0x{key_id:08X}UL
#define LIFETRAC_FLEET_KEY_BYTES \\
    {{ {row0}, \\
       {row1}, \\
       {row2}, \\
       {row3} }}

#endif
""".format(
        key_id=key_id,
        row0=rows[0].strip(),
        row1=rows[1].strip(),
        row2=rows[2].strip(),
        row3=rows[3].strip(),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--key", help="32 hex chars. Omit to generate a new random key.")
    parser.add_argument("--key-id", type=lambda value: int(value, 0), help="override 32-bit key id")
    parser.add_argument("--out", type=Path, default=DEFAULT_HEADER, help="output key.h path")
    parser.add_argument("--print-key", action="store_true", help="print generated key hex once")
    args = parser.parse_args()

    key = parse_key(args.key)
    key_id = args.key_id if args.key_id is not None else default_key_id(key)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_header(key, key_id), encoding="ascii")
    print(f"wrote {args.out}")
    print(f"key_id=0x{key_id:08X}")
    if args.print_key:
        print(f"key={key.hex()}")


if __name__ == "__main__":
    main()